//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use crate::{js_bindgen, r#macro};
use crate::JsValue;

pub(super) fn closure_unref(callback: &JsValue) {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "closure_unref", shim =
		"js_sys.closure_unref", inputs = [("arg0", & JsValue)],),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "closure_unref",
		required_embeds = [("js_sys", "closure.unref"), r#macro::js_input_embed::<&JsValue>()],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['closure.unref']", indirect_call =
			"this.#jsEmbed.js_sys['closure.unref'](arg0_0)", inputs = [("arg0", & JsValue)],
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.closure_unref"]
		fn closure_unref(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(callback);
		unsafe { closure_unref(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}
