[package]
name = "js-sys-bindgen"
version = "0.1.0"
edition = { workspace = true }
rust-version = "1.87"
license = { workspace = true }
include = { workspace = true }

[lib]
bench = false
doctest = false

[dependencies]
foldhash = { workspace = true, optional = true }
hashbrown = { workspace = true, optional = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = [
	"clone-impls",
	"extra-traits",
	"full",
	"parsing",
	"printing",
] }
weedle2 = { workspace = true, optional = true }
xxhash-rust = { workspace = true }

[dev-dependencies]
inline-snap = { workspace = true }
prettyplease = { workspace = true }

[features]
web-idl = ["dep:foldhash", "dep:hashbrown", "dep:weedle2"]

[lints]
workspace = true
