//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use js_sys::wire;
use js_sys::JsValue;
use js_sys::hazard::JsCast;

pub fn log0() {
	unsafe extern "C" {
		#[link_name = "web_sys.console.log0"]
		fn log0();
	}

	{ unsafe { log0() } };
}

pub fn log<T: JsCast>(data: &[T]) {
	unsafe extern "C" {
		#[link_name = "web_sys.console.log"]
		fn log(
			arg0_0: wire::InputSlot1<&[JsValue]>,
			arg0_1: wire::InputSlot2<&[JsValue]>,
			arg0_2: wire::InputSlot3<&[JsValue]>,
			arg0_3: wire::InputSlot4<&[JsValue]>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = unsafe { wire::split_input_as::<&[JsValue]>(data) };
		unsafe { log(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}

pub fn log2(data1: &JsValue, data2: &JsValue) {
	unsafe extern "C" {
		#[link_name = "web_sys.console.log2"]
		fn log2(
			arg0_0: wire::InputSlot1<&JsValue>,
			arg0_1: wire::InputSlot2<&JsValue>,
			arg0_2: wire::InputSlot3<&JsValue>,
			arg0_3: wire::InputSlot4<&JsValue>,
			arg1_0: wire::InputSlot1<&JsValue>,
			arg1_1: wire::InputSlot2<&JsValue>,
			arg1_2: wire::InputSlot3<&JsValue>,
			arg1_3: wire::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = wire::split_input::<&JsValue>(data1);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = wire::split_input::<&JsValue>(data2);
		unsafe { log2(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3) }
	};
}

pub fn error(data: &JsValue) {
	unsafe extern "C" {
		#[link_name = "web_sys.console.error"]
		fn error(
			arg0_0: wire::InputSlot1<&JsValue>,
			arg0_1: wire::InputSlot2<&JsValue>,
			arg0_2: wire::InputSlot3<&JsValue>,
			arg0_3: wire::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = wire::split_input::<&JsValue>(data);
		unsafe { error(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}

pub fn error1(data: &JsValue) -> u128 {
	unsafe extern "C" {
		#[link_name = "web_sys.console.error1"]
		fn error1(
			arg0_0: wire::InputSlot1<&JsValue>,
			arg0_1: wire::InputSlot2<&JsValue>,
			arg0_2: wire::InputSlot3<&JsValue>,
			arg0_3: wire::InputSlot4<&JsValue>,
		) -> wire::OutputRet<u128>;
	}

	wire::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = wire::split_input::<&JsValue>(data);
		unsafe { error1(arg0_0, arg0_1, arg0_2, arg0_3) }
	})
}
const _: () = {
	const TABLE: &wire::WireImportTypeTable = &wire::WireImportTypeTable::new(
		wire::wire_import_retptr_type(),
		&[wire::wire_import_input_type::<&[JsValue]>(), wire::wire_import_input_type::<&JsValue>()],
		&[wire::wire_import_output_type::<u128>()],
		wire::wire_import_catch(),
	);
	pub const WIRE: wire::Wire = wire::Wire::imports(
		TABLE,
		&[
			wire::WireImport::new(
				"web_sys",
				"console.log0",
				&[],
				::core::option::Option::None,
				::core::option::Option::Some(
					wire::WireImportBinding::new(
						::core::option::Option::None,
						"globalThis.console.log()",
						&[],
					),
				),
				false,
			),
			wire::WireImport::new(
				"web_sys",
				"console.log",
				&[wire::WireImportInput::new("arg0", 0usize)],
				::core::option::Option::None,
				::core::option::Option::Some(
					wire::WireImportBinding::new(
						::core::option::Option::None,
						"globalThis.console.log(arg0_0)",
						&[],
					),
				),
				false,
			),
			wire::WireImport::new(
				"web_sys",
				"console.log2",
				&[
					wire::WireImportInput::new("arg0", 1usize),
					wire::WireImportInput::new("arg1", 1usize),
				],
				::core::option::Option::None,
				::core::option::Option::Some(
					wire::WireImportBinding::new(
						::core::option::Option::None,
						"globalThis.console.log(arg0_0, arg1_0)",
						&[],
					),
				),
				false,
			),
			wire::WireImport::new(
				"web_sys",
				"console.error",
				&[wire::WireImportInput::new("arg0", 1usize)],
				::core::option::Option::None,
				::core::option::Option::Some(
					wire::WireImportBinding::new(
						::core::option::Option::None,
						"globalThis.console.error(arg0_0)",
						&[],
					),
				),
				false,
			),
			wire::WireImport::new(
				"web_sys",
				"console.error1",
				&[wire::WireImportInput::new("arg0", 1usize)],
				::core::option::Option::Some(wire::WireImportOutput::new(0usize)),
				::core::option::Option::Some(
					wire::WireImportBinding::new(
						::core::option::Option::None,
						"globalThis.console.error1(arg0_0)",
						&[],
					),
				),
				false,
			),
		],
	);
	pub const LEN: ::core::primitive::usize = wire::wire_blob_len(&WIRE);

	#[used]
	#[unsafe(link_section = "js_bindgen.wire")]
	pub static WIRE_SECTION: wire::WireBlob<LEN> = wire::WireBlob::new(&WIRE);
};
