//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use js_sys::r#macro;
use js_sys::JsValue;
use js_sys::hazard::JsCast;

pub fn log0() {
	unsafe extern "C" {
		#[link_name = "web_sys.console.log0"]
		fn log0();
	}

	{ unsafe { log0() } };
}

pub fn log<T: JsCast>(data: &[T]) {
	unsafe extern "C" {
		#[link_name = "web_sys.console.log"]
		fn log(
			arg0_0: r#macro::InputSlot1<&[JsValue]>,
			arg0_1: r#macro::InputSlot2<&[JsValue]>,
			arg0_2: r#macro::InputSlot3<&[JsValue]>,
			arg0_3: r#macro::InputSlot4<&[JsValue]>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = unsafe {
			r#macro::split_input_as::<&[JsValue]>(data)
		};
		unsafe { log(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}

pub fn log2(data1: &JsValue, data2: &JsValue) {
	unsafe extern "C" {
		#[link_name = "web_sys.console.log2"]
		fn log2(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
			arg1_0: r#macro::InputSlot1<&JsValue>,
			arg1_1: r#macro::InputSlot2<&JsValue>,
			arg1_2: r#macro::InputSlot3<&JsValue>,
			arg1_3: r#macro::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(data1);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<&JsValue>(data2);
		unsafe { log2(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3) }
	};
}

pub fn error(data: &JsValue) {
	unsafe extern "C" {
		#[link_name = "web_sys.console.error"]
		fn error(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(data);
		unsafe { error(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}
const _: () = {
	const IMPORTS: &[r#macro::ImportDescriptor] = &[
		r#macro::ImportDescriptor::new(
			"web_sys",
			"console.log0",
			"web_sys.console.log0",
			&[],
			::core::option::Option::None,
			::core::option::Option::Some(r#macro::ImportJs {
				direct_wrapper: true,
				direct_call: "globalThis.console.log()",
				indirect_call: "globalThis.console.log()",
				required_embeds: &[],
			}),
		),
		r#macro::ImportDescriptor::new(
			"web_sys",
			"console.log",
			"web_sys.console.log",
			&[r#macro::import_input::<&[JsValue]>("arg0")],
			::core::option::Option::None,
			::core::option::Option::Some(r#macro::ImportJs {
				direct_wrapper: true,
				direct_call: "globalThis.console.log(arg0_0)",
				indirect_call: "globalThis.console.log(arg0_0)",
				required_embeds: &[r#macro::js_input_embed::<&[JsValue]>()],
			}),
		),
		r#macro::ImportDescriptor::new(
			"web_sys",
			"console.log2",
			"web_sys.console.log2",
			&[r#macro::import_input::<&JsValue>("arg0"), r#macro::import_input::<&JsValue>("arg1")],
			::core::option::Option::None,
			::core::option::Option::Some(r#macro::ImportJs {
				direct_wrapper: true,
				direct_call: "globalThis.console.log(arg0_0, arg1_0)",
				indirect_call: "globalThis.console.log(arg0_0, arg1_0)",
				required_embeds: &[r#macro::js_input_embed::<&JsValue>()],
			}),
		),
		r#macro::ImportDescriptor::new(
			"web_sys",
			"console.error",
			"web_sys.console.error",
			&[r#macro::import_input::<&JsValue>("arg0")],
			::core::option::Option::None,
			::core::option::Option::Some(r#macro::ImportJs {
				direct_wrapper: true,
				direct_call: "globalThis.console.error(arg0_0)",
				indirect_call: "globalThis.console.error(arg0_0)",
				required_embeds: &[r#macro::js_input_embed::<&JsValue>()],
			}),
		),
	];
	const WAT_CAPACITY: ::core::primitive::usize = r#macro::import_wat_capacity(IMPORTS);

	#[used]
	#[unsafe(link_section = "js_bindgen.wat")]
	static WAT_SECTION: r#macro::ImportSection<WAT_CAPACITY> = r#macro::import_wat::<
		WAT_CAPACITY,
	>(IMPORTS);
	const JS_CAPACITY: ::core::primitive::usize = r#macro::import_js_capacity(IMPORTS);
	#[used]
	#[unsafe(link_section = "js_bindgen.import")]
	static JS_SECTION: r#macro::ImportSection<JS_CAPACITY> = r#macro::import_js::<
		JS_CAPACITY,
	>(IMPORTS);
};
