//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use core::marker::PhantomData;
use crate::JsValue;
use crate::hazard::{IntoJS, JsCast};

#[repr(transparent)]
pub struct JsNumber<T = f64> {
	value: JsValue,
	_type: PhantomData<T>,
}

impl<T> AsRef<JsValue> for JsNumber<T> {
	fn as_ref(&self) -> &JsValue {
		&self.value
	}
}

impl<T> From<JsNumber<T>> for JsValue {
	fn from(value: JsNumber<T>) -> Self {
		value.value
	}
}

unsafe impl<T> JsCast for JsNumber<T> {}

unsafe impl<T> IntoJS for JsNumber<T> {
	type Abi = <JsValue as IntoJS>::Abi;

	fn into_abi(self) -> Self::Abi {
		IntoJS::into_abi(JsValue::from(self))
	}
}
